# Generated by Django 6.0.1 on 2026-01-29 21:08

import deg_analysis.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_type', models.CharField(choices=[('BULK', 'Bulk RNA-seq'), ('SCRNA', 'Single-cell RNA-seq')], default='BULK', max_length=10)),
                ('data_file', models.FileField(upload_to=deg_analysis.models.upload_to)),
                ('is_normalized', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
